-- 코드를 입력하세요
SELECT 
    fp.PRODUCT_ID AS PRODUCT_ID,
    fp.PRODUCT_NAME AS PRODUCT_NAME,
    (fp.PRICE * SUM(fo.AMOUNT)) AS TOTAL_SALES
    # fo.PRODUCE_DATE
FROM 
    FOOD_PRODUCT AS fp
JOIN
    FOOD_ORDER AS fo
ON
    fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE 
    fo.PRODUCE_DATE LIKE '2022-05%'
GROUP BY
    fp.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    PRODUCT_ID ASC