WITH RECURSIVE TimeTable AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TimeTable WHERE HOUR < 23
)

SELECT
    A.HOUR,
    COUNT(B.DATETIME) AS COUNT
FROM TimeTable AS A
LEFT JOIN ANIMAL_OUTS AS B
ON A.HOUR = HOUR(B.DATETIME)
GROUP BY A.HOUR
ORDER BY A.HOUR